//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DaltinkurtModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DaltinkurtEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DaltinkurtEntities object using the connection string found in the 'DaltinkurtEntities' section of the application configuration file.
        /// </summary>
        public DaltinkurtEntities() : base("name=DaltinkurtEntities", "DaltinkurtEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DaltinkurtEntities object.
        /// </summary>
        public DaltinkurtEntities(string connectionString) : base(connectionString, "DaltinkurtEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DaltinkurtEntities object.
        /// </summary>
        public DaltinkurtEntities(EntityConnection connection) : base(connection, "DaltinkurtEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<adminda> adminda
        {
            get
            {
                if ((_adminda == null))
                {
                    _adminda = base.CreateObjectSet<adminda>("adminda");
                }
                return _adminda;
            }
        }
        private ObjectSet<adminda> _adminda;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dostsiteler> dostsiteler
        {
            get
            {
                if ((_dostsiteler == null))
                {
                    _dostsiteler = base.CreateObjectSet<dostsiteler>("dostsiteler");
                }
                return _dostsiteler;
            }
        }
        private ObjectSet<dostsiteler> _dostsiteler;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<hakkimda> hakkimda
        {
            get
            {
                if ((_hakkimda == null))
                {
                    _hakkimda = base.CreateObjectSet<hakkimda>("hakkimda");
                }
                return _hakkimda;
            }
        }
        private ObjectSet<hakkimda> _hakkimda;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<iletisim> iletisim
        {
            get
            {
                if ((_iletisim == null))
                {
                    _iletisim = base.CreateObjectSet<iletisim>("iletisim");
                }
                return _iletisim;
            }
        }
        private ObjectSet<iletisim> _iletisim;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<kategoriyazilar> kategoriyazilar
        {
            get
            {
                if ((_kategoriyazilar == null))
                {
                    _kategoriyazilar = base.CreateObjectSet<kategoriyazilar>("kategoriyazilar");
                }
                return _kategoriyazilar;
            }
        }
        private ObjectSet<kategoriyazilar> _kategoriyazilar;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<menuler> menuler
        {
            get
            {
                if ((_menuler == null))
                {
                    _menuler = base.CreateObjectSet<menuler>("menuler");
                }
                return _menuler;
            }
        }
        private ObjectSet<menuler> _menuler;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rightbar_menuler> rightbar_menuler
        {
            get
            {
                if ((_rightbar_menuler == null))
                {
                    _rightbar_menuler = base.CreateObjectSet<rightbar_menuler>("rightbar_menuler");
                }
                return _rightbar_menuler;
            }
        }
        private ObjectSet<rightbar_menuler> _rightbar_menuler;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sidemenulink> sidemenulink
        {
            get
            {
                if ((_sidemenulink == null))
                {
                    _sidemenulink = base.CreateObjectSet<sidemenulink>("sidemenulink");
                }
                return _sidemenulink;
            }
        }
        private ObjectSet<sidemenulink> _sidemenulink;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<yazilarim> yazilarim
        {
            get
            {
                if ((_yazilarim == null))
                {
                    _yazilarim = base.CreateObjectSet<yazilarim>("yazilarim");
                }
                return _yazilarim;
            }
        }
        private ObjectSet<yazilarim> _yazilarim;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<siteekle> siteekle
        {
            get
            {
                if ((_siteekle == null))
                {
                    _siteekle = base.CreateObjectSet<siteekle>("siteekle");
                }
                return _siteekle;
            }
        }
        private ObjectSet<siteekle> _siteekle;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tavsiyesiteler> tavsiyesiteler
        {
            get
            {
                if ((_tavsiyesiteler == null))
                {
                    _tavsiyesiteler = base.CreateObjectSet<tavsiyesiteler>("tavsiyesiteler");
                }
                return _tavsiyesiteler;
            }
        }
        private ObjectSet<tavsiyesiteler> _tavsiyesiteler;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the adminda EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToadminda(adminda adminda)
        {
            base.AddObject("adminda", adminda);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dostsiteler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodostsiteler(dostsiteler dostsiteler)
        {
            base.AddObject("dostsiteler", dostsiteler);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the hakkimda EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohakkimda(hakkimda hakkimda)
        {
            base.AddObject("hakkimda", hakkimda);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the iletisim EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToiletisim(iletisim iletisim)
        {
            base.AddObject("iletisim", iletisim);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the kategoriyazilar EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTokategoriyazilar(kategoriyazilar kategoriyazilar)
        {
            base.AddObject("kategoriyazilar", kategoriyazilar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the menuler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomenuler(menuler menuler)
        {
            base.AddObject("menuler", menuler);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rightbar_menuler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorightbar_menuler(rightbar_menuler rightbar_menuler)
        {
            base.AddObject("rightbar_menuler", rightbar_menuler);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sidemenulink EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosidemenulink(sidemenulink sidemenulink)
        {
            base.AddObject("sidemenulink", sidemenulink);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the yazilarim EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToyazilarim(yazilarim yazilarim)
        {
            base.AddObject("yazilarim", yazilarim);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the siteekle EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTositeekle(siteekle siteekle)
        {
            base.AddObject("siteekle", siteekle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tavsiyesiteler EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotavsiyesiteler(tavsiyesiteler tavsiyesiteler)
        {
            base.AddObject("tavsiyesiteler", tavsiyesiteler);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaltinkurtModel", Name="adminda")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class adminda : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new adminda object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="kullaniciAdi">Initial value of the KullaniciAdi property.</param>
        /// <param name="sifre">Initial value of the Sifre property.</param>
        /// <param name="gecerlilik">Initial value of the Gecerlilik property.</param>
        public static adminda Createadminda(global::System.Int32 id, global::System.String kullaniciAdi, global::System.String sifre, global::System.String gecerlilik)
        {
            adminda adminda = new adminda();
            adminda.ID = id;
            adminda.KullaniciAdi = kullaniciAdi;
            adminda.Sifre = sifre;
            adminda.Gecerlilik = gecerlilik;
            return adminda;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String KullaniciAdi
        {
            get
            {
                return _KullaniciAdi;
            }
            set
            {
                OnKullaniciAdiChanging(value);
                ReportPropertyChanging("KullaniciAdi");
                _KullaniciAdi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("KullaniciAdi");
                OnKullaniciAdiChanged();
            }
        }
        private global::System.String _KullaniciAdi;
        partial void OnKullaniciAdiChanging(global::System.String value);
        partial void OnKullaniciAdiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sifre
        {
            get
            {
                return _Sifre;
            }
            set
            {
                OnSifreChanging(value);
                ReportPropertyChanging("Sifre");
                _Sifre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sifre");
                OnSifreChanged();
            }
        }
        private global::System.String _Sifre;
        partial void OnSifreChanging(global::System.String value);
        partial void OnSifreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gecerlilik
        {
            get
            {
                return _Gecerlilik;
            }
            set
            {
                OnGecerlilikChanging(value);
                ReportPropertyChanging("Gecerlilik");
                _Gecerlilik = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gecerlilik");
                OnGecerlilikChanged();
            }
        }
        private global::System.String _Gecerlilik;
        partial void OnGecerlilikChanging(global::System.String value);
        partial void OnGecerlilikChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaltinkurtModel", Name="dostsiteler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dostsiteler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dostsiteler object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="ad">Initial value of the ad property.</param>
        /// <param name="url">Initial value of the url property.</param>
        /// <param name="oncelik">Initial value of the oncelik property.</param>
        public static dostsiteler Createdostsiteler(global::System.Int32 id, global::System.String ad, global::System.String url, global::System.Int32 oncelik)
        {
            dostsiteler dostsiteler = new dostsiteler();
            dostsiteler.ID = id;
            dostsiteler.ad = ad;
            dostsiteler.url = url;
            dostsiteler.oncelik = oncelik;
            return dostsiteler;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ad
        {
            get
            {
                return _ad;
            }
            set
            {
                OnadChanging(value);
                ReportPropertyChanging("ad");
                _ad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ad");
                OnadChanged();
            }
        }
        private global::System.String _ad;
        partial void OnadChanging(global::System.String value);
        partial void OnadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 oncelik
        {
            get
            {
                return _oncelik;
            }
            set
            {
                OnoncelikChanging(value);
                ReportPropertyChanging("oncelik");
                _oncelik = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("oncelik");
                OnoncelikChanged();
            }
        }
        private global::System.Int32 _oncelik;
        partial void OnoncelikChanging(global::System.Int32 value);
        partial void OnoncelikChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaltinkurtModel", Name="hakkimda")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class hakkimda : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new hakkimda object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="baslik">Initial value of the baslik property.</param>
        /// <param name="detay">Initial value of the detay property.</param>
        /// <param name="oncelik">Initial value of the oncelik property.</param>
        public static hakkimda Createhakkimda(global::System.Int64 id, global::System.String baslik, global::System.String detay, global::System.Int64 oncelik)
        {
            hakkimda hakkimda = new hakkimda();
            hakkimda.ID = id;
            hakkimda.baslik = baslik;
            hakkimda.detay = detay;
            hakkimda.oncelik = oncelik;
            return hakkimda;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String baslik
        {
            get
            {
                return _baslik;
            }
            set
            {
                OnbaslikChanging(value);
                ReportPropertyChanging("baslik");
                _baslik = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("baslik");
                OnbaslikChanged();
            }
        }
        private global::System.String _baslik;
        partial void OnbaslikChanging(global::System.String value);
        partial void OnbaslikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String detay
        {
            get
            {
                return _detay;
            }
            set
            {
                OndetayChanging(value);
                ReportPropertyChanging("detay");
                _detay = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("detay");
                OndetayChanged();
            }
        }
        private global::System.String _detay;
        partial void OndetayChanging(global::System.String value);
        partial void OndetayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 oncelik
        {
            get
            {
                return _oncelik;
            }
            set
            {
                OnoncelikChanging(value);
                ReportPropertyChanging("oncelik");
                _oncelik = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("oncelik");
                OnoncelikChanged();
            }
        }
        private global::System.Int64 _oncelik;
        partial void OnoncelikChanging(global::System.Int64 value);
        partial void OnoncelikChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaltinkurtModel", Name="iletisim")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class iletisim : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new iletisim object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="ad_Soyad">Initial value of the Ad_Soyad property.</param>
        /// <param name="e_posta">Initial value of the E_posta property.</param>
        /// <param name="telefon">Initial value of the Telefon property.</param>
        /// <param name="yorum">Initial value of the Yorum property.</param>
        public static iletisim Createiletisim(global::System.Int32 id, global::System.String ad_Soyad, global::System.String e_posta, global::System.String telefon, global::System.String yorum)
        {
            iletisim iletisim = new iletisim();
            iletisim.ID = id;
            iletisim.Ad_Soyad = ad_Soyad;
            iletisim.E_posta = e_posta;
            iletisim.Telefon = telefon;
            iletisim.Yorum = yorum;
            return iletisim;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ad_Soyad
        {
            get
            {
                return _Ad_Soyad;
            }
            set
            {
                OnAd_SoyadChanging(value);
                ReportPropertyChanging("Ad_Soyad");
                _Ad_Soyad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ad_Soyad");
                OnAd_SoyadChanged();
            }
        }
        private global::System.String _Ad_Soyad;
        partial void OnAd_SoyadChanging(global::System.String value);
        partial void OnAd_SoyadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String E_posta
        {
            get
            {
                return _E_posta;
            }
            set
            {
                OnE_postaChanging(value);
                ReportPropertyChanging("E_posta");
                _E_posta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("E_posta");
                OnE_postaChanged();
            }
        }
        private global::System.String _E_posta;
        partial void OnE_postaChanging(global::System.String value);
        partial void OnE_postaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telefon
        {
            get
            {
                return _Telefon;
            }
            set
            {
                OnTelefonChanging(value);
                ReportPropertyChanging("Telefon");
                _Telefon = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telefon");
                OnTelefonChanged();
            }
        }
        private global::System.String _Telefon;
        partial void OnTelefonChanging(global::System.String value);
        partial void OnTelefonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Yorum
        {
            get
            {
                return _Yorum;
            }
            set
            {
                OnYorumChanging(value);
                ReportPropertyChanging("Yorum");
                _Yorum = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Yorum");
                OnYorumChanged();
            }
        }
        private global::System.String _Yorum;
        partial void OnYorumChanging(global::System.String value);
        partial void OnYorumChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaltinkurtModel", Name="kategoriyazilar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class kategoriyazilar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new kategoriyazilar object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="adi">Initial value of the Adi property.</param>
        /// <param name="gozukurluk">Initial value of the gozukurluk property.</param>
        public static kategoriyazilar Createkategoriyazilar(global::System.Int32 id, global::System.String adi, global::System.String gozukurluk)
        {
            kategoriyazilar kategoriyazilar = new kategoriyazilar();
            kategoriyazilar.Id = id;
            kategoriyazilar.Adi = adi;
            kategoriyazilar.gozukurluk = gozukurluk;
            return kategoriyazilar;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Adi
        {
            get
            {
                return _Adi;
            }
            set
            {
                OnAdiChanging(value);
                ReportPropertyChanging("Adi");
                _Adi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Adi");
                OnAdiChanged();
            }
        }
        private global::System.String _Adi;
        partial void OnAdiChanging(global::System.String value);
        partial void OnAdiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gozukurluk
        {
            get
            {
                return _gozukurluk;
            }
            set
            {
                OngozukurlukChanging(value);
                ReportPropertyChanging("gozukurluk");
                _gozukurluk = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gozukurluk");
                OngozukurlukChanged();
            }
        }
        private global::System.String _gozukurluk;
        partial void OngozukurlukChanging(global::System.String value);
        partial void OngozukurlukChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaltinkurtModel", Name="menuler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class menuler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new menuler object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="menuAd">Initial value of the menuAd property.</param>
        /// <param name="oncelik">Initial value of the oncelik property.</param>
        /// <param name="gozukurluk">Initial value of the gozukurluk property.</param>
        /// <param name="url">Initial value of the url property.</param>
        public static menuler Createmenuler(global::System.Int32 id, global::System.String menuAd, global::System.Int32 oncelik, global::System.String gozukurluk, global::System.String url)
        {
            menuler menuler = new menuler();
            menuler.ID = id;
            menuler.menuAd = menuAd;
            menuler.oncelik = oncelik;
            menuler.gozukurluk = gozukurluk;
            menuler.url = url;
            return menuler;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String menuAd
        {
            get
            {
                return _menuAd;
            }
            set
            {
                OnmenuAdChanging(value);
                ReportPropertyChanging("menuAd");
                _menuAd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("menuAd");
                OnmenuAdChanged();
            }
        }
        private global::System.String _menuAd;
        partial void OnmenuAdChanging(global::System.String value);
        partial void OnmenuAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 oncelik
        {
            get
            {
                return _oncelik;
            }
            set
            {
                OnoncelikChanging(value);
                ReportPropertyChanging("oncelik");
                _oncelik = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("oncelik");
                OnoncelikChanged();
            }
        }
        private global::System.Int32 _oncelik;
        partial void OnoncelikChanging(global::System.Int32 value);
        partial void OnoncelikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gozukurluk
        {
            get
            {
                return _gozukurluk;
            }
            set
            {
                OngozukurlukChanging(value);
                ReportPropertyChanging("gozukurluk");
                _gozukurluk = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gozukurluk");
                OngozukurlukChanged();
            }
        }
        private global::System.String _gozukurluk;
        partial void OngozukurlukChanging(global::System.String value);
        partial void OngozukurlukChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaltinkurtModel", Name="rightbar_menuler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rightbar_menuler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rightbar_menuler object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="menuAd">Initial value of the menuAd property.</param>
        /// <param name="oncelik">Initial value of the oncelik property.</param>
        /// <param name="gozukurluk">Initial value of the gozukurluk property.</param>
        /// <param name="url">Initial value of the url property.</param>
        public static rightbar_menuler Createrightbar_menuler(global::System.Int32 id, global::System.String menuAd, global::System.Int32 oncelik, global::System.String gozukurluk, global::System.String url)
        {
            rightbar_menuler rightbar_menuler = new rightbar_menuler();
            rightbar_menuler.ID = id;
            rightbar_menuler.menuAd = menuAd;
            rightbar_menuler.oncelik = oncelik;
            rightbar_menuler.gozukurluk = gozukurluk;
            rightbar_menuler.url = url;
            return rightbar_menuler;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String menuAd
        {
            get
            {
                return _menuAd;
            }
            set
            {
                OnmenuAdChanging(value);
                ReportPropertyChanging("menuAd");
                _menuAd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("menuAd");
                OnmenuAdChanged();
            }
        }
        private global::System.String _menuAd;
        partial void OnmenuAdChanging(global::System.String value);
        partial void OnmenuAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 oncelik
        {
            get
            {
                return _oncelik;
            }
            set
            {
                OnoncelikChanging(value);
                ReportPropertyChanging("oncelik");
                _oncelik = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("oncelik");
                OnoncelikChanged();
            }
        }
        private global::System.Int32 _oncelik;
        partial void OnoncelikChanging(global::System.Int32 value);
        partial void OnoncelikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gozukurluk
        {
            get
            {
                return _gozukurluk;
            }
            set
            {
                OngozukurlukChanging(value);
                ReportPropertyChanging("gozukurluk");
                _gozukurluk = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gozukurluk");
                OngozukurlukChanged();
            }
        }
        private global::System.String _gozukurluk;
        partial void OngozukurlukChanging(global::System.String value);
        partial void OngozukurlukChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaltinkurtModel", Name="sidemenulink")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sidemenulink : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sidemenulink object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="linkAd">Initial value of the linkAd property.</param>
        /// <param name="oncelik">Initial value of the oncelik property.</param>
        /// <param name="url">Initial value of the url property.</param>
        public static sidemenulink Createsidemenulink(global::System.Int32 id, global::System.String linkAd, global::System.Int32 oncelik, global::System.String url)
        {
            sidemenulink sidemenulink = new sidemenulink();
            sidemenulink.ID = id;
            sidemenulink.linkAd = linkAd;
            sidemenulink.oncelik = oncelik;
            sidemenulink.url = url;
            return sidemenulink;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String linkAd
        {
            get
            {
                return _linkAd;
            }
            set
            {
                OnlinkAdChanging(value);
                ReportPropertyChanging("linkAd");
                _linkAd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("linkAd");
                OnlinkAdChanged();
            }
        }
        private global::System.String _linkAd;
        partial void OnlinkAdChanging(global::System.String value);
        partial void OnlinkAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 oncelik
        {
            get
            {
                return _oncelik;
            }
            set
            {
                OnoncelikChanging(value);
                ReportPropertyChanging("oncelik");
                _oncelik = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("oncelik");
                OnoncelikChanged();
            }
        }
        private global::System.Int32 _oncelik;
        partial void OnoncelikChanging(global::System.Int32 value);
        partial void OnoncelikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaltinkurtModel", Name="siteekle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class siteekle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new siteekle object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="adi">Initial value of the adi property.</param>
        /// <param name="url">Initial value of the url property.</param>
        /// <param name="bolum">Initial value of the bolum property.</param>
        public static siteekle Createsiteekle(global::System.Int32 id, global::System.String adi, global::System.String url, global::System.String bolum)
        {
            siteekle siteekle = new siteekle();
            siteekle.ID = id;
            siteekle.adi = adi;
            siteekle.url = url;
            siteekle.bolum = bolum;
            return siteekle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adi
        {
            get
            {
                return _adi;
            }
            set
            {
                OnadiChanging(value);
                ReportPropertyChanging("adi");
                _adi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("adi");
                OnadiChanged();
            }
        }
        private global::System.String _adi;
        partial void OnadiChanging(global::System.String value);
        partial void OnadiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bolum
        {
            get
            {
                return _bolum;
            }
            set
            {
                OnbolumChanging(value);
                ReportPropertyChanging("bolum");
                _bolum = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("bolum");
                OnbolumChanged();
            }
        }
        private global::System.String _bolum;
        partial void OnbolumChanging(global::System.String value);
        partial void OnbolumChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaltinkurtModel", Name="tavsiyesiteler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tavsiyesiteler : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tavsiyesiteler object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="adi">Initial value of the adi property.</param>
        /// <param name="url">Initial value of the url property.</param>
        /// <param name="oncelik">Initial value of the oncelik property.</param>
        public static tavsiyesiteler Createtavsiyesiteler(global::System.Int32 id, global::System.String adi, global::System.String url, global::System.Int32 oncelik)
        {
            tavsiyesiteler tavsiyesiteler = new tavsiyesiteler();
            tavsiyesiteler.ID = id;
            tavsiyesiteler.adi = adi;
            tavsiyesiteler.url = url;
            tavsiyesiteler.oncelik = oncelik;
            return tavsiyesiteler;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adi
        {
            get
            {
                return _adi;
            }
            set
            {
                OnadiChanging(value);
                ReportPropertyChanging("adi");
                _adi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("adi");
                OnadiChanged();
            }
        }
        private global::System.String _adi;
        partial void OnadiChanging(global::System.String value);
        partial void OnadiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 oncelik
        {
            get
            {
                return _oncelik;
            }
            set
            {
                OnoncelikChanging(value);
                ReportPropertyChanging("oncelik");
                _oncelik = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("oncelik");
                OnoncelikChanged();
            }
        }
        private global::System.Int32 _oncelik;
        partial void OnoncelikChanging(global::System.Int32 value);
        partial void OnoncelikChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DaltinkurtModel", Name="yazilarim")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class yazilarim : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new yazilarim object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="kategoriId">Initial value of the KategoriId property.</param>
        /// <param name="baslik">Initial value of the Baslik property.</param>
        /// <param name="icerik">Initial value of the Icerik property.</param>
        /// <param name="kayitTarihi">Initial value of the kayitTarihi property.</param>
        public static yazilarim Createyazilarim(global::System.Int32 id, global::System.Int32 kategoriId, global::System.String baslik, global::System.String icerik, global::System.String kayitTarihi)
        {
            yazilarim yazilarim = new yazilarim();
            yazilarim.ID = id;
            yazilarim.KategoriId = kategoriId;
            yazilarim.Baslik = baslik;
            yazilarim.Icerik = icerik;
            yazilarim.kayitTarihi = kayitTarihi;
            return yazilarim;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KategoriId
        {
            get
            {
                return _KategoriId;
            }
            set
            {
                OnKategoriIdChanging(value);
                ReportPropertyChanging("KategoriId");
                _KategoriId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KategoriId");
                OnKategoriIdChanged();
            }
        }
        private global::System.Int32 _KategoriId;
        partial void OnKategoriIdChanging(global::System.Int32 value);
        partial void OnKategoriIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Baslik
        {
            get
            {
                return _Baslik;
            }
            set
            {
                OnBaslikChanging(value);
                ReportPropertyChanging("Baslik");
                _Baslik = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Baslik");
                OnBaslikChanged();
            }
        }
        private global::System.String _Baslik;
        partial void OnBaslikChanging(global::System.String value);
        partial void OnBaslikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ozet
        {
            get
            {
                return _Ozet;
            }
            set
            {
                OnOzetChanging(value);
                ReportPropertyChanging("Ozet");
                _Ozet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ozet");
                OnOzetChanged();
            }
        }
        private global::System.String _Ozet;
        partial void OnOzetChanging(global::System.String value);
        partial void OnOzetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Etiketler
        {
            get
            {
                return _Etiketler;
            }
            set
            {
                OnEtiketlerChanging(value);
                ReportPropertyChanging("Etiketler");
                _Etiketler = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Etiketler");
                OnEtiketlerChanged();
            }
        }
        private global::System.String _Etiketler;
        partial void OnEtiketlerChanging(global::System.String value);
        partial void OnEtiketlerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Icerik
        {
            get
            {
                return _Icerik;
            }
            set
            {
                OnIcerikChanging(value);
                ReportPropertyChanging("Icerik");
                _Icerik = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Icerik");
                OnIcerikChanged();
            }
        }
        private global::System.String _Icerik;
        partial void OnIcerikChanging(global::System.String value);
        partial void OnIcerikChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String kayitTarihi
        {
            get
            {
                return _kayitTarihi;
            }
            set
            {
                OnkayitTarihiChanging(value);
                ReportPropertyChanging("kayitTarihi");
                _kayitTarihi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("kayitTarihi");
                OnkayitTarihiChanged();
            }
        }
        private global::System.String _kayitTarihi;
        partial void OnkayitTarihiChanging(global::System.String value);
        partial void OnkayitTarihiChanged();

        #endregion
    
    }

    #endregion
    
}
